### ISSUE TITLE
details.yml has a line missing

### ISSUE THREAD

**Issue by Walckiers** [mrzool/letter-boilerplate#1]
details.yml reads
    mainfont: Hoefler Text
    sansfont: Helvetica Neue

But this results in an error message
    ! Font \zf@basefont= at 10.0pt not loadable: Bad metric (TFM) file.
    \zf@fontspec ...ntname \zf@suffix " at \f@size pt
                                                      \unless \ifzf@icu \zf@set@...
    l.34 ...[Ligatures={Common}, Numbers={OldStyle}]{}

```
pandoc: Error producing PDF from TeX source
make: *** [output.pdf] Error 43
```

This error can be cured by adding this line to details.yml4
    monofont: DejaVu Sans Mono

Apologies for lack of Markdown styling ...

**Comment by mrzool** [comment]
Fixed, thanks!
