### ISSUE TITLE
make with following error?

### ISSUE THREAD

**Issue by cryoguy** [mrzool/letter-boilerplate#12]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "Hoefler Text" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.36 ...Common}, Numbers={OldStyle}]{Hoefler Text}

pandoc: Error producing PDF
make: *** [makefile:7: output.pdf] Error 43

**Comment by mrzool** [comment]
Hoefler Text is not installed on your system. Use a font that you have installed. More info [here](http://mrzool.cc/writing/typesetting-automation/#playing-with-the-settings).
