### ISSUE TITLE
No creation rule for font "Hoefler Text"

### ISSUE THREAD

**Issue by mallim** [mrzool/letter-boilerplate#16]
Running on windows, with Miktext and pandoc 2.1.3 will throw this error.

**Comment by mrzool** [comment]
Hoefler Text is a commercial typeface that doesn’t come preinstalled on Windows. Do you have this font installed on your system?

**Comment by mallim** [comment]
nope. how to change it to another font?

**Comment by mrzool** [comment]
Read the docs.
