### ISSUE TITLE
Please consider adding letterhead.pdf to this repository

### ISSUE THREAD

**Issue by carsten-j** [mrzool/letter-boilerplate#18]
Thanks for the great work. Would it be possible to add the letterhead.pdf file to this repository so I can try the transformation example described here:
https://mrzool.cc/writing/typesetting-automation/

**Comment by elbym** [comment]
This file is your personal stationery template. I see no benefit in adding a generic “ACME Inc.” stationary to the repo.

**Comment by carsten-j** [comment]
I have some troubles getting my own letterhead.pdf aligned correctly. That is why I was curious to see a generic letterhead such that one could see the placement and exactly location of the text in such an example.

**Comment by mrzool** [comment]
@elbym is right, it would make no sense to include that letterhead in the repo. I would be happy to send it to you privately to help you out, but that’s something I put together on the fly in inDesign years ago and I have no idea where to find that file anymore. Sorry :/

**Comment by elbym** [comment]
@carsten-j try this pdf: https://github.com/elbym/public-files/blob/master/mm%20paper%20DIN%20A4.pdf

**Comment by carsten-j** [comment]
@elbym thanks. This will be really helpful. Much appreciated.
