### ISSUE TITLE
Craftadoc template

### ISSUE THREAD

**Issue by Loosetooth** [mrzool/letter-boilerplate#21]
Hi @mrzool ,
I'd like to reach out this way to let you know that I've converted your `letter-boilerplate` template into a Craftadoc template, which I called [Simple Letter](https://app.craftadoc.com/template/overview/637cd3b3e354f40a11cd752c). This integration enables anyone to fill in your template in the browser, opening up new possibilities for individuals who may not be familiar with LaTeX.

You can find the fork of the latex project at [Simple Letter](https://github.com/Craftadoc/simple-letter).

If you have the time and interest to check it out, I'd be happy to hear any thoughts or criticism.

Thanks so much for creating this template, and being so generous to make it open source and sharing it!

**Comment by mrzool** [comment]
Hey @Loosetooth, nice one! I didn't know about Craftadoc. Any project that helps folks with their administrative needs is a good one in my book. Thanks for letting me know about your port!
