### ISSUE TITLE
Support YAML metadata block

### ISSUE THREAD

**Issue by infotexture** [mrzool/letter-boilerplate#7]
Rather than requiring an additional `details.yml` file to specify sender/recipient details & settings, consider adding an option to include metadata in a [YAML metadata block](http://pandoc.org/README.html#extension-yaml_metadata_block) in the Markdown file.

This approach is supported by several other Markdown-aware tools such as [Jekyll](http://jekyllrb.com/docs/frontmatter/) and [Marked](http://marked2app.com/help/Per-Document_Settings.html#metadataformat).

**Comment by mrzool** [comment]
That makes a lot of sense. Will look into it.

**Comment by mrzool** [comment]
Your idea is now implemented. Thanks for the suggestion!

**Comment by JZL** [comment]
Hi, sorry if you're just getting around to this but this would be great as well on the other boilerplates as well. I've used them for some of my own papers and I love these repos!

**Comment by mrzool** [comment]
@JZL How do you mean? My [other](https://github.com/mrzool/cv-boilerplate) [boilerplates](https://github.com/mrzool/invoice-boilerplate) have more structured content and don't require any markdown.

**Comment by JZL** [comment]
I'm sorry, I misunderstood the commits. Nevermind!

**Comment by mrzool** [comment]
👍 no worries!

**Comment by infotexture** [comment]
Nice, thanks.
